name: Run tests for pull requests to develop

on:
  pull_request:
    branches:
      - develop

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Running tests with Maven
        run: mvn test